#!/bin/bash
echo "choose the number of files: "
read files_number;
for i in $(seq 1 $files_number); do
	fileName=exercise$i.php;
	touch $fileName;
	echo "<?php" > $fileName;
	echo "file $fileName created";
done;
